import re

with open("wos-formula-refiner.html", "r", encoding="utf-8") as f:
    code = f.read()

# 1. Add Tab Button
old_tabs = """    <div class="tabs">
      <button class="tab-btn active" onclick="switchTab('predict')">🔮 Predict</button>
      <button class="tab-btn" onclick="switchTab('data')">📈 Data & Curve</button>
    </div>"""

new_tabs = """    <div class="tabs">
      <button class="tab-btn active" onclick="switchTab('predict')">🔮 Predict</button>
      <button class="tab-btn" onclick="switchTab('data')">📈 Data & Curve</button>
      <button class="tab-btn" onclick="switchTab('formula')">📐 Formula Engine</button>
    </div>"""
code = code.replace(old_tabs, new_tabs)

# 2. Add Tab Container (right before <script>)
tab_formula = """
  <div id="tab-formula" class="tab-content">
    <div class="card">
      <h2>📐 Live Tier Models</h2>
      <p style="font-size: 13px; color: var(--muted); margin-top:0;">The live cubic polynomials generated by the ML pipeline.</p>
      <div id="tierModelsContainer"></div>
    </div>
    
    <div class="card">
      <h2>🔍 Boundary Diagnostics</h2>
      <p style="font-size: 13px; color: var(--muted); margin-top:0;">Live metrics from the dynamic tier-splitting algorithm.</p>
      <div id="boundaryContainer"></div>
    </div>
    
    <div class="card">
      <h2>🔗 Continuity Checks</h2>
      <p style="font-size: 13px; color: var(--muted); margin-top:0;">Verifies the smoothness of the curve across tier boundaries.</p>
      <div id="continuityContainer"></div>
    </div>
  </div>
"""
code = code.replace("  <script>", tab_formula + "\n  <script>")

# 3. Add JS function to populate formula tab
js_func = """
  function renderFormulaTab() {
    // 1. Render Tiers
    const tierCont = document.getElementById('tierModelsContainer');
    if (typeof TIER_FORMULAS === 'undefined' || TIER_FORMULAS.length === 0) {
      tierCont.innerHTML = '<div class="result-desc">No tier models found.</div>';
    } else {
      let html = '';
      TIER_FORMULAS.forEach((tier, i) => {
        const badgeColor = tier.provisional ? '#ff9800' : '#4caf50';
        const badgeText = tier.provisional ? 'Provisional' : 'Verified';
        const badge = `<span style="font-size:11px; padding:3px 8px; border-radius:12px; background:${badgeColor}; color:white; font-weight:600;">${badgeText}</span>`;
        
        let c = tier.coeffs;
        let cStr = '';
        if (c && c.length === 4) {
           cStr = `Damage = (${fmt(c[0])})*L³ + (${fmt(c[1])})*L² + (${fmt(c[2])})*L + (${fmt(c[3])})`;
        }
        
        html += `<div style="background:#f8f9fa; border:1px solid #ddd; padding:12px; border-radius:6px; margin-bottom:12px;">
                   <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;">
                     <div style="font-weight:bold; font-size:16px;">Tier ${i+1}: Levels ${tier.range[0]} - ${tier.range[1]}</div>
                     ${badge}
                   </div>
                   <div style="font-size:13px; color:var(--text); margin-bottom:8px;">
                     <strong>Points:</strong> ${tier.n_points} | <strong>Train Max Error:</strong> ${tier.max_error_pct}% | <strong>LOOCV Error:</strong> ${tier.loocv_max_pct}%
                   </div>
                   <div style="background:#282c34; color:#abb2bf; padding:8px; border-radius:4px; font-family:monospace; font-size:12px; overflow-x:auto;">
                     ${cStr}
                   </div>
                 </div>`;
      });
      tierCont.innerHTML = html;
    }

    // 2. Render Boundaries
    const bndCont = document.getElementById('boundaryContainer');
    if (typeof BOUNDARY_METADATA === 'undefined' || Object.keys(BOUNDARY_METADATA).length === 0) {
      bndCont.innerHTML = '<div class="result-desc">No dynamic boundaries detected.</div>';
    } else {
      let html = '';
      for (const [bnd, meta] of Object.entries(BOUNDARY_METADATA)) {
        let stableBadge = meta.stable ? `<span style="color:#4caf50; font-weight:bold;">[Stable]</span>` : `<span style="color:#ff9800; font-weight:bold;">[Unstable]</span>`;
        
        let peltStr = '';
        if (meta.pelt_disagree) {
           peltStr = `<div style="margin-top:6px; color:#d84315; font-size:12px;"><strong>⚠️ Method Disagreement:</strong> BIC selected ${bnd}, but PELT suggested ${meta.pelt_suggestions.join(', ')}. Boundary is actively shifting.</div>`;
        } else {
           peltStr = `<div style="margin-top:6px; color:#4caf50; font-size:12px;"><strong>✅ Method Consensus:</strong> BIC and PELT agree on this boundary.</div>`;
        }

        html += `<div style="border-left: 3px solid #2196f3; padding-left: 10px; margin-bottom: 12px;">
                   <div style="font-weight:bold; font-size:14px;">Boundary at Level ${bnd} ${stableBadge}</div>
                   ${peltStr}
                 </div>`;
      }
      bndCont.innerHTML = html;
    }

    // 3. Render Continuity Checks
    const contCont = document.getElementById('continuityContainer');
    if (typeof TIER_FORMULAS === 'undefined' || TIER_FORMULAS.length <= 1) {
      contCont.innerHTML = '<div class="result-desc">Only one tier exists. No continuity checks required.</div>';
    } else {
      let html = '';
      for (let i = 0; i < TIER_FORMULAS.length - 1; i++) {
        let t1 = TIER_FORMULAS[i];
        let t2 = TIER_FORMULAS[i+1];
        
        let l1 = t1.range[1];
        let l2 = t2.range[0];
        
        if (l2 - l1 > 2) {
          html += `<div style="font-size:13px; color:#ff9800;">Gap between Tier ${i+1} (ends ${l1}) and Tier ${i+2} (starts ${l2}) is too wide to check strictly.</div>`;
          continue;
        }

        let hp1 = t1.coeffs[0]*Math.pow(l1,3) + t1.coeffs[1]*Math.pow(l1,2) + t1.coeffs[2]*l1 + t1.coeffs[3];
        let hp2 = t2.coeffs[0]*Math.pow(l2,3) + t2.coeffs[1]*Math.pow(l2,2) + t2.coeffs[2]*l2 + t2.coeffs[3];
        
        let growth = ((hp2 - hp1) / hp1) * 100;
        let color = (growth > 0 && growth < 100) ? '#4caf50' : '#d84315';
        
        html += `<div style="display:flex; justify-content:space-between; border-bottom:1px solid #eee; padding:8px 0; font-size:13px;">
                   <span>Transition <strong>L${l1} ➡️ L${l2}</strong>:</span>
                   <span style="font-family:monospace; color:${color}; font-weight:bold;">Damage +${growth.toFixed(1)}%</span>
                 </div>`;
      }
      contCont.innerHTML = html;
    }
  }
"""

old_render = "  function renderTable() {"
code = code.replace(old_render, js_func + "\n" + old_render)

# Call renderFormulaTab in the onload section
old_onload = """    renderTable();
    renderChart();
  };"""
new_onload = """    renderTable();
    renderChart();
    renderFormulaTab();
  };"""
code = code.replace(old_onload, new_onload)

with open("wos-formula-refiner.html", "w", encoding="utf-8") as f:
    f.write(code)
